# Generated by Django 5.0.2 on 2024-10-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('telegram_id', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='maker_profile/')),
            ],
        ),
    ]
